# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb8835bc05850d54d0dca429a71063e36363981a2b0bf29f3c26703e25552b73c65df21cb932fd2c7dbeb2401c8664429d66da04c1e6ce7cbe1337991a0a8f2e

test:
  secret_key_base: 67bf423e4e5806a473876e8edde244b65643501908ec3deb4c49121882857ed66a79c9f5821187138d47fe69e10ba9b0f80bdc6537ab14732ab9eac5892d34ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
